In [2]:
class Human:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def printinfo(self):
        print(self.name)
        print(self.age)




ono = Human('小野', 54)
tanaka = Human('田中', 30)

ono.printinfo()
tanaka.printinfo()

print(ono.name)
print(tanaka.name)

#インスタンス変数にデータを入れる
tanaka.age += 1 # 現在の値に1追加する
print(tanaka.age) # 31
tanaka.printinfo() # 田中、31

小野
54
田中
30
小野
田中
31
田中
31